name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh                          # Ensure the .ssh folder exists
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa # Write the private key
        chmod 600 ~/.ssh/id_rsa                 # Set strict permissions

    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && nvm use 18 && cd /home/wiki/ && git pull origin main && npm run docs:build"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}